# Generated by Django 3.0.3 on 2020-04-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='folled_by',
            new_name='followed_by',
        ),
    ]
