# Generated by Django 3.0.3 on 2020-04-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200408_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='/static/all/default-cover.png', upload_to='social/profile/cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/static/all/user.png', upload_to='social/profile/pic'),
        ),
    ]
