# Generated by Django 3.0.3 on 2020-04-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200408_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='/social/profile/cover/default-cover.png', upload_to='social/profile/cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/social/profile/pic/user.png', upload_to='social/profile/pic'),
        ),
    ]
