# Generated by Django 3.0.3 on 2020-04-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
