# Generated by Django 3.0.3 on 2020-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20200411_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
