# Generated by Django 3.0.3 on 2020-04-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20200411_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
    ]
