# Generated by Django 3.0.3 on 2020-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resized',
            field=models.BooleanField(default=False),
        ),
    ]
