# Generated by Django 3.0.3 on 2020-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_post_resized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='private',
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
