# Generated by Django 3.0.3 on 2020-04-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_auto_20200417_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
