# Generated by Django 3.0.3 on 2020-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
