# Generated by Django 3.0.3 on 2020-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_auto_20200419_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
