# Generated by Django 3.0.3 on 2020-04-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0029_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='followed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=300)),
                ('jr_college', models.CharField(default='', max_length=300)),
                ('college', models.CharField(default='', max_length=300)),
                ('job', models.CharField(default='', max_length=200)),
                ('movie', models.CharField(default='', max_length=300)),
                ('song', models.CharField(default='', max_length=300)),
                ('book', models.CharField(default='', max_length=300)),
                ('colour', models.CharField(default='', max_length=200)),
                ('fruit', models.CharField(default='', max_length=200)),
                ('food', models.CharField(default='', max_length=200)),
                ('game', models.CharField(default='', max_length=200)),
                ('place', models.CharField(default='', max_length=200)),
                ('singer', models.CharField(default='', max_length=200)),
                ('actor', models.CharField(default='', max_length=200)),
                ('player', models.CharField(default='', max_length=200)),
                ('prof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='social.profile')),
            ],
        ),
    ]
