# Generated by Django 3.0.3 on 2020-04-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0031_auto_20200419_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(default='social/profile/cover/default-cover.png', upload_to='social/profile/cover'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='social/profile/pic/user.png', upload_to='social/profile/pic'),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(default='', max_length=2000)),
                ('seen', models.BooleanField(default=False)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
                ('sen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
