# Generated by Django 3.0.3 on 2020-04-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0033_chatfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sen',
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='social.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='rec',
            field=models.BooleanField(default=False),
        ),
    ]
