# Generated by Django 3.0.3 on 2020-04-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0035_auto_20200422_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='seenChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgg', models.TextField(default='', max_length=2000)),
                ('recc', models.BooleanField(default=False)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('user11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.profile')),
                ('user22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
